### ISSUE TITLE
maybe_create_thumbnail

### ISSUE THREAD

**Issue by tobyink** [ChaoticEvil/p5-ithumb-xs#1]
It would be pretty good to have a maybe_create_thumbnail function that did this:

- if `dst_file` does not exist, then create thumbnail;
- if `dst_file` is zero bytes, then create thumbnail;
- if modified date of `dst_file` is older than modified date of `src_file`, then create thumnail;
- otherwise, do nothing.

**Comment by ChaoticEvil** [comment]
Interesting offer). However, it looks like some kind of business logic for periodically traversing files and performing some kind of operation. Roughly speaking, put a job in cron and she decided whether to perform file conversion or not. I fantasize about using the function you are talking about :).

I think that implementations of such logic go beyond the framework of a minimalist library and fall on the shoulders of the developer who uses this library in his project. So, I don’t think that now there is a need for this function in the library itself. Maybe in the future, but not now.

P.S. Sorry. My English is very prim.
