### ISSUE TITLE
messing with CCFLAGS, got loadable library and perl binaries are mismatched on i686

### ISSUE THREAD

**Issue by viy2** [ChaoticEvil/p5-ithumb-xs#3]
Makefile.PL overrides CCFLAGS, causing loadable library and perl binaries mismatch on i686:

XS.c: loadable library and perl binaries are mismatched (got handshake key 0x9040080, needed 0x90c0080)
t/create_thumbnail.t ..
Dubious, test returned 1 (wstat 256, 0x100)

to fix, include perl's $Config{ccflags}

--- Makefile.PL
+++ Makefile.PL
@@ -3,7 +3,7 @@
 use ExtUtils::MakeMaker;
+use Config;
                                                                                                                                                                                              
@@ -12,7 +12,7 @@
     LIBS              => ['-lImlib2'],
     DEFINE            => '',
     INC               => '-I/usr/include -I/usr/X11/include/',
-    CCFLAGS           => '-Wall -Wextra -Werror -std=c11',
+    CCFLAGS           => $Config{ccflags}.' -Wall -Wextra -Werror -std=c11',
     OPTIMIZE          => '-O3',
     META_MERGE        => {
         'meta-spec' => {

**Comment by ChaoticEvil** [comment]
@viy2 Thank you for bug report. Fixed in https://github.com/ChaoticEvil/p5-ithumb-xs/commit/ae1808aff872372e6f1da7462180aee67a693942

**Comment by viy2** [comment]
thanks!

**Comment by viy2** [comment]
thanks, built successfully for ALTLinux.
http://autoimports.altlinux.org/pub/ALTLinux/autoimports/Sisyphus/files/SRPMS/perl-Ithumb-XS-0.5.5-alt1.src.rpm
